version: '3.8'

services:
  schedule_organizerbot:
    build: .
    container_name: schedule_organizerbot
    env_file:
      - token.env
    restart: unless-stopped
    volumes:
      - .:/app
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge
